version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: finance-db
    environment:
      MYSQL_DATABASE: financedb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./Personal_Money_management_backend
      dockerfile: Dockerfile
    image: finance-backend:latest
    container_name: finance-backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/financedb?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build:
      context: ./Personal_money_management_Frontend
      dockerfile: Dockerfile
    image: finance-frontend:latest
    container_name: finance-frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: